### ISSUE TITLE
When called from a different directory, rng2doc fails to find relaxng.rng

### ISSUE THREAD

**Issue by sknorr** [openSUSE/rng2doc#57]
This works:

```
(env) ~/data/gits/rng2doc > rng2doc -f html -o ~/data/gits/geekodoc/geekodoc/rng/r2d2 \
  ~/data/gits/geekodoc/geekodoc/rng/geekodoc5-flat.rng

```

This fails:
```
(env) ~/data/gits/geekodoc/geekodoc/rng > rng2doc -f html -o r2d2 geekodoc5-flat.rng

Traceback (most recent call last):
  File "/home/sknorr-l/data/gits/rng2doc/env/bin/rng2doc", line 33, in <module>
    sys.exit(load_entry_point('rng2doc', 'console_scripts', 'rng2doc')())
  File "/home/sknorr-l/data/gits/rng2doc/src/rng2doc/cli.py", line 123, in main
    result = parse(args['RNGFILE'])
  File "/home/sknorr-l/data/gits/rng2doc/src/rng2doc/rng.py", line 125, in parse
    relaxng_schema = etree.parse("schemas/relaxng.rng")
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file 'schemas/relaxng.rng': failed to load external entity "schemas/relaxng.rng"
```

**Comment by OBITORASU** [comment]
Any hints on how I should approach this issue?

**Comment by sknorr** [comment]
@OBITORASU There's probably just a relative path string somewhere that needs to be prepended with the correct path to the Python module or a path under `/usr/share/` where the RNG schema can be stored.

**Comment by OBITORASU** [comment]
Ok I will try and take a look and report back what I found.

**Comment by OBITORASU** [comment]
Had a small question regarding this issue.
What is the behavior of the program for these two cases:
- ```(env) ~/data/gits/geekodoc/geekodoc/rng > rng2doc -f html -o r2d2  ~/data/gits/geekodoc/geekodoc/rng/geekodoc5-flat.rng```
- ```(env) ~/data/gits/geekodoc/geekodoc/rng > rng2doc -f html -o ~/data/gits/geekodoc/geekodoc/rng/r2d2  geekodoc5-flat.rng```
If possible please share, thank you!
